spring:
    application:
        name: payserver
    mvc:
        view:
          prefix: /WEB-INF/views/
          suffix: .jsp

eureka:
     instance:
        preferIpAddress: true
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true


server:
    port: 8080
